In [1]:
import pandas as pd

In [2]:
kim_data = pd.read_excel("../data/references/kim2010/kim2010_supp_table1.xls")

In [3]:
kim_data.head()

,Systemic ID,Gene name,KO%,Deletion dataset,Analysis dataset,Published phenotype,UP-tag sequence,DOWN-tag sequence,cp5,cp3,...,Construction method,Gene function,Paralog,Sc ortholog,Gene number relationship Sp|Sc,Copy number relationship Sp|Sc,Dispensibility relationship Sp|Sc,Species distribution,Archaeal related not in bacteria,Heterozygous diploid containing ts mutation (being remade)
0,SPAC1002.01,NaN,88.0,V,V,nodata,GCTTGGTTAGTGGACGCCCG,CAGGAAACATTACGCCGCCC,TCACCCCTCTCTTGATTTAGTAACA,GGTTTATGAAGGGAAGAAGCTTTCG,...,serial,conserved fungal protein,none,YPL041C,1|1,one|one,v|v,c_f,NaN,NaN
1,SPAC1002.02,mug31,92.0,V,V,nodata,TGGTTTCAGGACATGGCGGA,AGGGGGATTGTCGAAGCGGG,GCTACCAGGCGAATATCTTCAAAAA,ATGTCTCAGTTGATGACAGTGGATG,...,block,nucleoporin Pom34 (predicted),none,YLR018C,1|1,one|one,v|v,c_f,NaN,NaN
2,SPAC1002.03c,gls2,98.0,V,V,viable,CTAGGCGGCACGGGTTCAAA,CGCGCCGGCATATTACGTTT,TGCTGTTGTCCAAGCATATTTCGTA,CTTCCCGTAAAGCTGAAAACGTTAA,...,block,glucosidase II Gls2,none,YBR229C,1|1,one|one,v|v,c_e,NaN,NaN
3,SPAC1002.04c,taf11,91.0,E,E,nodata,AGCACAGGCCGCGATTATGA,ACCCGGGACGAAGTCAAGCA,CAGCATTGCAAAGCATTTTCATACT,ATTACGAAATATGCTTGGACAACAG,...,serial,transcription factor TFIID complex subunit Taf11,none,YML015C,1|1,one|one,e|e,c_e,NaN,NaN
4,SPAC1002.05c,jmj2,98.0,V,V,nodata,TTCCCTCAAGACCCGCCTGC,AAAAGTGGAGGGGGCAGGGG,GTTGTTCCGATTGTAAATTCTATGC,CTTCTTGCCGATTCCAATTCTCTTT,...,block,histone demethylase Jmj2 (predicted),none,YJR119C,1|1,one|one,v|v,c_e,NaN,ts

In [4]:
kim_data.query("`Deletion dataset` != `Analysis dataset` and (`Deletion dataset`.notna() or `Analysis dataset`.notna())")

,Systemic ID,Gene name,KO%,Deletion dataset,Analysis dataset,Published phenotype,UP-tag sequence,DOWN-tag sequence,cp5,cp3,...,Construction method,Gene function,Paralog,Sc ortholog,Gene number relationship Sp|Sc,Copy number relationship Sp|Sc,Dispensibility relationship Sp|Sc,Species distribution,Archaeal related not in bacteria,Heterozygous diploid containing ts mutation (being remade)
206,SPAC13D6.05,alp11,54.0,V,E,essential,TCCACGCGGCACTCACTCTT,CCGAGTGGCCGAAGCAAACG,GATCATATGCGAAATGTAGTTGGTT,CATGCATCGTGATCATCTTTCATGT,...,block,tubulin specific chaperone cofactor B,none,YNL148C,1|1,one|one,e|v,c_e,NaN,NaN
310,SPAC1565.06c,spg1,99.0,V,E,essential,TCCGCACACGCCAGCATAAA,CGCGACGAATAGCCCCAGAG,CCAGAAAAAATAGTCCCGAACAAAC,TATTTCAGACCTTGTTTTCAACTGC,...,serial,GTPase Spg1,none,YML064C,1|1,one|one,e|e,c_e,NaN,NaN
759,SPAC1F7.04,rho1,48.0,V,E,essential,GACCCTCGGAACCTGCTCGC,ACCGAGGCGTCATTCCCAGC,AAATAGGATAAGCGGATTAAATGCG,GGCAATCCTTAACAAAAGAAACAAG,...,block,Rho family GTPase Rho1,SPAC20H4.11C,YPR165W,2|1,many|one,ev|e,c_e,NaN,NaN
1333,SPAC30D11.13,hus5,99.0,V,E,essential,TTTCCGCCCTTCTCAACCGA,GCACGGGGTGGTGGCATAGT,AGCATCTAGAGAAAAATCAATTGGC,ATTTTTGGTTGCTTAATGTTCTGAA,...,serial,SUMO conjugating enzyme Hus5,none,YDL064W,1|1,one|one,e|e,c_e,NaN,NaN
1531,SPAC3H8.10,spo2,59.0,V,E,essential,AACCAAAGCGCACCCTCGAT,GCCGCCGCACTCCTATCATT,TCTATCGTTCGTTTTTTTTGGTAAA,CGGATAATCTAGAATGGATGAAACA,...,block,sec14 cytosolic factor family Sec14,none,YKL091C|YMR079W,1|2,one|many,e|ve,c_e,NaN,NaN
2471,SPBC14C8.16c,bot1,81.0,V,E,essential,ACCAAGGCCGCACCGATGAT,GCTGCCTTACGCGGGATTGG,TGATGTGTCAATTGCCAAACAAAAA,AAAAGAAGAATTTGGACTTGACACA,...,block,mitochondrial ribosomal protein subunit S35,none,YGR165W,1|1,one|one,e|v,c_f,NaN,ts
2596,SPBC16C6.09,ogm4,94.0,E,V,viable,ACGGGCATGGTCGACGGCTA,TTTCCAAGGGCGGGCGAGTC,ACCTACTACGAAACGTGGAGAAATG,AGATATCAAGCTTCATGCAATAGCA,...,block,protein O-mannosyltransferase Ogm4,none,YJR143C,1|1,one|one,v|?,c_e,NaN,NaN
2722,SPBC1718.06,msp1,99.0,V,E,essential,CTTGCGGATCCATTTGCCCG,CCAGATCTCGAGCAGCCACG,CTCTTTCGCAATATCCATACCGAAC,TCGAATCTTGTTTACTTCGTCTAGC,...,serial,mitochondrial GTPase Msp1,none,YOR211C,1|1,one|one,e|v,c_e,NaN,NaN
2768,SPBC17A3.02,NaN,34.0,V,NaN,nodata,CAACACCCTCTCGCGCCTGG,TGAGGATAACCGGTGGGCGT,ATGTCAATGTCTGCACATTTATTGA,GACAGTGCAAGCTGCTACTGTGAAT,...,(GS),conserved fungal protein,none,YIL087C,1|1,one|one,?|v,c_f,NaN,NaN
3045,SPBC23G7.12c,rpt6,97.0,V,E,essential,AGGTCGGTGGGGGCAGTGTG,GCAGGGTAGGGCGGGGATTC,TTTTGCGAGTTAGCTTTGCTTAACC,ATGTGTATACGTACGATCGAAAACC,...,block,19S proteasome regulatory subunit Rpt6 (predic...,none,YGL048C,1|1,one|one,e|e,c_e,NaN,NaN
3300,SPBC32C12.02,ste11,99.0,E,V,viable,ACCTCGCAATCCCCAGCAAC,CATTTACCCGCTGCCCCACT,GAACTTGATTTCTTTGGCGAACAAG,CAATATATATGTAATAACGGGCCCA,...,serial,transcription factor Ste11,none,NONE,1|0,one|none,v|-,c_f,NaN,NaN
3307,SPBC32F12.06,pch1,99.0,V,E,essential,TGGAGCGGGGGAGGAAGGAA,CAACAAGACCCACGCCGAGA,TGTCAAGAATTAGGCAATTGTTGAT,TACGAAAATTCTCCGTATTGTTCGA,...,serial,cyclin Pch1,none,YLR226W,1|1,one|one,e|v,c_e,NaN,NaN
3417,SPBC36B7.07,tlg1,37.0,E,V,viable,CGCACGCCCTACCAAACGCT,GAACAGACGGGTGGGCGAGG,TTTTTTAGCACAAAGGCTAGAATGA,GAAGAGGACGATGATTTTGATGGAG,...,block,SNARE Tgl1,none,YDR468C,1|1,one|one,v|e,c_e,NaN,NaN
3855,SPBC8D2.20c,sec31,98.0,V,E,essential,GCGAAGAAAATGGCAGGGCG,CTTCCTGACCGCTCCCAACG,CGAGTTTTTGTTCCTTTATACTGCG,TTCATCGACTATCTCATCTCATCCG,...,block,COPII-coated vesicle component Sec31 (predicted),none,YDL195W,1|1,one|one,e|e,c_e,NaN,NaN
4249,SPCC1620.11,nup97,81.0,V,E,essential,TTACGGGAAGGTGGATGGGG,TGCCGTTCCTTTCTCGCCCT,AAATATCATTTCCCTATTGCTGTCC,CGAAATGGAGGAGGCTACAGAAATT,...,block,nucleoporin Nic96 homolog,SPCC1739.14,YFR002W,2|1,many|one,ev|e,c_e,NaN,NaN
4271,SPCC1682.07,ssl1,99.0,E,V,viable,GGGTCCAGATGTTTGCGGGG,CCTCATCCCCCGTTCTGCTG,AGACTGATAAACACGAATTAACGCA,TTCAGCAAATAATTCAACTTGGTCA,...,block,transcription factor TFIIH complex subunit Ssl1,none,YLR005W,1|1,one|one,v|e,c_e,NaN,NaN
4324,SPCC1739.07,NaN,89.0,V,E,essential,GCCAAGGGTGGGGCGAAATC,GGGGCGGGAGTCAATAGGCA,CGTCACTATATGTTCACATGTTCCA,AAAAACAAATTTTTCCACGTCTACG,...,block,substrate-specific nuclear cofactor for exosom...,none,YHR081W,1|1,one|one,e|v,c_e,NaN,NaN
4354,SPCC18.04,pof6,99.0,V,E,essential,GAGGTGGGCGACAGGGTAGG,GCAGGGGGACTTGGTCGGTC,ATCAATTAACATATGCTAAACCGCG,GTGTGGGATGTACGATCCAAAAAGA,...,block,F-box protein Pof6,none,YJL204C,1|1,one|one,e|v,c_f,NaN,NaN
4378,SPCC1840.02c,bgs4,99.0,V,E,essential,GTACAACTGCCGGCCTGCGA,GCCGGTAAAGCCATCGCCAC,GGGAATTCCTTCCTTTTTTTAGAAA,AGGTAAAAGTTTTGTGAACCAATGG,...,block,"1,3-beta-glucan synthase subunit Bgs4",SPBC19G7.05C|SPAC19B12.03|SPAC24C9.07C,YGR032W|YLR342W|YMR306W,4|3,many|many,eeev|vvv,c_f,NaN,NaN
4449,SPCC24B10.06,NaN,32.0,V,NaN,nodata,CTTTCACAGGCGAGCGAGCA,GCGGGAGGTGCGGATGAGAA,AAGATCAAATCTTTCGTGGACTTTT,ATGAAAAGAACGAAATTTGTTGAAA,...,(GS),sequence orphan,none,NONE,1|0,one|none,?|-,s_p,NaN,NaN
4810,SPCC777.10c,ubc12,92.0,V,E,essential,CCACACCCCGCCATCAAGTC,CGCGGGCTCTTCATCGTGTG,CTTTGAAACAGCTGTCGAAGTTGTA,AGGCAGTATGAAAGCACAAATGAAG,...,block,NEDD8-conjugating enzyme Ubc12,none,YLR306W,1|1,one|one,e|v,c_e,NaN,NaN

In [5]:
merge_data = pd.read_excel("../data/1_formatted/minimal_merge.xlsx")

In [6]:
merge_data.head()

,Systematic ID,Gene name,Gene product,Gene type,Kim_ID,Hayles_ID,Kim_Note,Hayles_Note,Kim_Deletion_dataset,Kim_Analysis_dataset,Kim_Paralog,Hayles_Deletion_mutant_phenotype_description,Hayles_Phenotypic_classification,Hayles_Gene_dispensability
0,SPAC1002.01,mrx11,mitochondrial expression network (MIOREX) comp...,protein coding gene,SPAC1002.01,SPAC1002.01,NO_CHANGE,NO_CHANGE,V,V,NaN,"VIABLE WT cells at 25,32",WT,V
1,SPAC1002.02,pom34,nucleoporin Pom34,protein coding gene,SPAC1002.02,SPAC1002.02,NO_CHANGE,NO_CHANGE,V,V,NaN,"VIABLE WT cells at 25,32",WT,V
2,SPAC1002.03c,gls2,glucosidase II alpha subunit Gls2,protein coding gene,SPAC1002.03c,SPAC1002.03c,NO_CHANGE,NO_CHANGE,V,V,NaN,"VIABLE WT cells at 25,32",WT,V
3,SPAC1002.04c,taf11,transcription factor TFIID complex subunit Taf11,protein coding gene,SPAC1002.04c,SPAC1002.04c,NO_CHANGE,NO_CHANGE,E,E,NaN,"ESSENTIAL microcolonies misshapen cells at 25,32",misshapen essential,E
4,SPAC1002.05c,jmj2,histone demethylase Jmj2,protein coding gene,SPAC1002.05c,SPAC1002.05c,NO_CHANGE,NO_CHANGE,V,V,NaN,"VIABLE WT cells at 25,32",WT,V

In [9]:
merge_data.query("Kim_Analysis_dataset != Hayles_Gene_dispensability and (Kim_Analysis_dataset.notna() or Hayles_Gene_dispensability.notna())")

,Systematic ID,Gene name,Gene product,Gene type,Kim_ID,Hayles_ID,Kim_Note,Hayles_Note,Kim_Deletion_dataset,Kim_Analysis_dataset,Kim_Paralog,Hayles_Deletion_mutant_phenotype_description,Hayles_Phenotypic_classification,Hayles_Gene_dispensability
117,SPAC11E3.12,SPAC11E3.12,"mitochondrial thioredoxin family protein, impl...",protein coding gene,SPAC11E3.12,SPAC11E3.12,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
257,SPAC144.08,jac1,mitochondrial [2Fe-2S] cluster assembly co-cha...,protein coding gene,SPAC144.08,SPAC144.08,NO_CHANGE,NO_CHANGE,V,V,NaN,ESSENTIAL microcolonies skittle slightly missh...,skittle,E
487,SPAC17C9.13c,cut8,tethering factor for nuclear proteasome Cut8,protein coding gene,SPAC17C9.13c,SPAC17C9.13c,NO_CHANGE,NO_CHANGE,E,E,NaN,"VIABLE slightly misshapen cells at 25, ESSENTI...",long high penetrance,V
649,SPAC19B12.13,cox1102,cytochrome c oxidase copper chaperone Cox1102/...,protein coding gene,SPAC19B12.13,NaN,NO_CHANGE,NaN,V,V,SPAC1420.04c,NaN,NaN,NaN
738,SPAC1F3.02c,mkh1,MEK kinase (MEKK) Mkh1,protein coding gene,SPAC1F3.02c,NaN,NO_CHANGE,NaN,V,V,NaN,NaN,NaN,NaN
759,SPAC1F7.04,rho1,Rho family GTPase Rho1,protein coding gene,SPAC1F7.04,SPAC1F7.04,NO_CHANGE,NO_CHANGE,V,E,SPAC20H4.11c,"VIABLE WT cells at 25,32",WT,V
815,SPAC21E11.06,tif224,translation initiation factor eIF2B delta subunit,protein coding gene,SPAC21E11.06,SPAC21E11.06,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL spores at 25,32",spores,E
880,SPAC22E12.16c,pik1,Golgi-specific 1-phosphatidylinositol 4-kinase...,protein coding gene,SPAC22E12.16c,SPAC22E12.16c,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"ESSENTIAL spores, germinated spores at 25,32",germination,E
942,SPAC23A1.10,tef102,translation elongation factor EF-1 alpha Ef1a-b,protein coding gene,SPAC23A1.10,NaN,NO_CHANGE,NaN,V,V,SPCC794.09c|SPBC839.15c,NaN,NaN,NaN
947,SPAC23A1.16c,rtr1,RNA polymerase II CTD phosphatase Rtr1,protein coding gene,SPAC23A1.16c,SPAC23A1.16c,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL germinated spores long misshapen, se...",long high penetrance,E
1089,SPAC25B8.06c,dia4,mitochondrial serine-tRNA ligase,protein coding gene,SPAC25B8.06c,SPAC25B8.06c,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL microcolonies skittle cells at 25,32",skittle,E
1095,SPAC25B8.12c,SPAC25B8.12c,"HAD superfamily hydrolase, unknown role",protein coding gene,SPAC25B8.12c,NaN,NO_CHANGE,NaN,V,V,NaN,NaN,NaN,NaN
1127,SPAC26A3.08,smb1,Sm snRNP core protein Smb1,protein coding gene,SPAC26A3.08,SPAC26A3.08,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"ESSENTIAL spores, germinated spores, occasiona...",germination,E
1265,SPAC2F3.06c,kap104,karyopherin/importin beta family nuclear impor...,protein coding gene,SPAC2F3.06c,SPAC2F3.06c,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL microcolonies misshapen cells at 25,32",misshapen essential,E
1332,SPAC30D11.13,hus5,SUMO conjugating enzyme E2 Hus5/Ubc9,protein coding gene,SPAC30D11.13,SPAC30D11.13,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE small colonies long cells at 25,32",long high penetrance,V
1418,SPAC3A11.08,cul4,"CLRC complex subunit, cullin 4",protein coding gene,SPAC3A11.08,SPAC3A11.08,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL microcolonies long cells at 25,32, c...",long high penetrance,E
1485,SPAC3G9.03,rpl2301,60S ribosomal protein L23,protein coding gene,SPAC3G9.03,SPAC3G9.03,NO_CHANGE,NO_CHANGE,NaN,NaN,SPCC1322.11,"VIABLE small colonies WT cells at 25,32",WT,V
1520,SPAC3H5.11,SPAC3H5.11,NAD/NADH kinase,protein coding gene,SPAC3H5.11,SPAC3H5.11,NO_CHANGE,NO_CHANGE,V,V,SPCC24B10.02c|SPAC1B1.02c,"ESSENTIAL microcolonies long cells at 25,32",long high penetrance,E
1530,SPAC3H8.10,spo20,"sec14 cytosolic factor family, phospholipid-in...",protein coding gene,SPAC3H8.10,SPAC3H8.10,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE small colonies stubby cells at 25,32",stubby,V
1839,SPAC6C3.09,rpp40,RNase P and RNase MRP subunit Rpp40,protein coding gene,SPAC6C3.09,SPAC6C3.09,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL spores, germinated spores, often mis...",misshapen essential,E
1875,SPAC6G10.05c,trs120,TRAPP II complex subunit Trs120,protein coding gene,SPAC6G10.05c,SPAC6G10.05c,NO_CHANGE,NO_CHANGE,V,V,NaN,ESSENTIAL germinated spores slightly misshapen...,misshapen essential,E
1906,SPAC750.08c,SPAC750.08c,"NAD-dependent malic enzyme (predicted), partial",protein coding gene,SPAC750.08c,SPAC750.08c,NO_CHANGE,NO_CHANGE,NaN,NaN,SPCC794.12c,"VIABLE small colonies WT cells at 25,32",WT,V
1949,SPAC823.12,vps11,HOPs/CORVET complex ubiquitin protein ligase E...,protein coding gene,SPAC823.12,SPAC823.12,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL microcolonies misshapen cells at 25,32",misshapen essential,E
1959,SPAC824.06,pam18,PAM complex DNAJ subunit Pam18/Tim14,protein coding gene,SPAC824.06,SPAC824.06,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"ESSENTIAL microcolonies skittle cells at 25,32",skittle,E
2050,SPAC977.06,SPAC977.06,S. pombe specific DUF999 family protein 3,protein coding gene,SPAC977.06,SPAC977.06,NO_CHANGE,NO_CHANGE,NaN,NaN,SPAC212.04c|SPAC750.06c|SPBC1348.01|SPAC212.01...,"VIABLE WT cells at 25,32",WT,V
2051,SPAC977.07c,pfl6,"cell surface glycoprotein, flocculin Pfl6",protein coding gene,SPAC977.07c,NaN,NO_CHANGE,NaN,V,V,SPAPB2C8.01|SPAC1F8.06|SPBC1348.08c|SPCC188.09c,NaN,NaN,NaN
2062,SPAC9E9.04,SPAC9E9.04,"bcap family homolog, implicated in a chaperone...",protein coding gene,SPAC9E9.04,SPAC9E9.04,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
2389,SPBC1347.01c,rev1,deoxycytidyl transferase Rev1,protein coding gene,SPBC1347.01c,SPBC1347.01c,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
2470,SPBC14C8.16c,bot1,mitochondrial ribosomal protein subunit S45,protein coding gene,SPBC14C8.16c,SPBC14C8.16c,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE WT cells at 25,32",WT,V
2611,SPBC16E9.01c,php4,CCAAT-binding factor complex repressor Php4,protein coding gene,SPBC16E9.01c,SPBC16E9.01c,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
2721,SPBC1718.06,msp1,mitochondrial dynamin family fusion GTPase Msp1,protein coding gene,SPBC1718.06,SPBC1718.06,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE WT cells at 25,32",WT,V
2767,SPBC17A3.02,aim19,mitochondrial membrane protein involved in hem...,protein coding gene,SPBC17A3.02,SPBC17A3.02,NO_CHANGE,NO_CHANGE,V,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
3044,SPBC23G7.12c,rpt6,19S proteasome base subcomplex ATPase subunit ...,protein coding gene,SPBC23G7.12c,SPBC23G7.12c,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE WT cells at 25,32",WT,V
3299,SPBC32C12.02,ste11,DNA-binding transcription factor Ste11,protein coding gene,SPBC32C12.02,SPBC32C12.02,NO_CHANGE,NO_CHANGE,E,V,NaN,ESSENTIAL microcolonies slightly misshapen cel...,misshapen essential,E
3352,SPBC337.13c,gtr1,RagA/B GTPase Gtr1,protein coding gene,SPBC337.13c,SPBC337.13c,NO_CHANGE,NO_CHANGE,V,V,NaN,ESSENTIAL microcolonies slightly misshapen cel...,misshapen essential,E
3416,SPBC36B7.07,tlg1,late Golgi membrane t-SNARE Tlg1,protein coding gene,SPBC36B7.07,SPBC36B7.07,NO_CHANGE,NO_CHANGE,E,V,NaN,"ESSENTIAL spores at 25,32",spores,E
3505,SPBC405.01,ade1,phosphoribosylamine-glycine ligase/phosphoribo...,protein coding gene,SPBC405.01,SPBC405.01,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
3637,SPBC577.10,pre4,"20S proteasome complex subunit beta 7, Pre4",protein coding gene,SPBC577.10,SPBC577.10,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL spores, germinated spores long at 25,32",long high penetrance,E
3777,SPBC800.09,sum2,translational repressor Sum2,protein coding gene,SPBC800.09,SPBC800.09,NO_CHANGE,NO_CHANGE,E,E,NaN,"VIABLE WT cells at 25,32",WT,V
3854,SPBC8D2.20c,sec31,COPII-coated vesicle component Sec31,protein coding gene,SPBC8D2.20c,SPBC8D2.20c,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE WT cells at 25,32",WT,V
4089,SPCC1235.01,SPCC1235.01,cell surface glycoprotein,protein coding gene,SPCC1235.01,SPCC1235.01,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
4270,SPCC1682.07,ssl1,transcription factor TFIIH complex subunit Ssl1,protein coding gene,SPCC1682.07,SPCC1682.07,NO_CHANGE,NO_CHANGE,E,V,NaN,ESSENTIAL microcolonies misshapen branched sep...,long branched,E
4279,SPCC1682.16,rpt4,19S proteasome base subcomplex ATPase subunit ...,protein coding gene,SPCC1682.16,SPCC1682.16,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
4281,SPCC16A11.02,utp13,"small subunit processome, U3 snoRNP-associated...",protein coding gene,SPCC16A11.02,NaN,NO_CHANGE,NaN,E,E,NaN,NaN,NaN,NaN
4312,SPCC16C4.16c,cbc3,nuclear cap-binding complex variant subunit Cbc3,protein coding gene,SPCC16C4.16c,NaN,NO_CHANGE,NaN,V,V,NaN,NaN,NaN,NaN
4323,SPCC1739.07,cti1,exosome C1D family subunit Cti1,protein coding gene,SPCC1739.07,SPCC1739.07,NO_CHANGE,NO_CHANGE,V,E,NaN,"VIABLE very small colonies WT cells at 25,32",WT,V
4328,SPCC1739.12,ppe1,serine/threonine protein phosphatase PP6 catal...,protein coding gene,SPCC1739.12,SPCC1739.12,NO_CHANGE,NO_CHANGE,E,E,NaN,"VIABLE small colonies rounded cells at 25,32",rounded,V
4329,SPCC1739.13,ssa2,Hsp70 family heat shock protein Ssa2,protein coding gene,SPCC1739.13,SPCC1739.13,NO_CHANGE,NO_CHANGE,V,V,SPAC13G7.02c,"ESSENTIAL spores at 25,32",spores,E
4377,SPCC1840.02c,bgs4,"cell wall and secondary septum 1,6 branched 1,...",protein coding gene,SPCC1840.02c,SPCC1840.02c,NO_CHANGE,NO_CHANGE,V,E,SPBC19G7.05c|SPAC19B12.03|SPAC24C9.07c,"VIABLE WT cells at 25,32",WT,V
4448,SPCC24B10.06,SPCC24B10.06,"Schizosaccharomyces specific protein, predicte...",protein coding gene,SPCC24B10.06,SPCC24B10.06,NO_CHANGE,NO_CHANGE,V,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
4506,SPCC320.04c,gem1,ERMES complex GTPase subunit Gem1,protein coding gene,SPCC320.04c,SPCC320.04c,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells with some long cells at 25,32",long low penetrance,V
4577,SPCC4B3.14,cwf20,complexed with Cdc5 protein Cwf20,protein coding gene,SPCC4B3.14,SPCC4B3.14,NO_CHANGE,NO_CHANGE,V,V,NaN,"ESSENTIAL microcolonies long cells at 25,32",long high penetrance,E
4579,SPCC4B3.16,tip41,TIP41 type 2a phosphatase regulator Tip41,protein coding gene,SPCC4B3.16,SPCC4B3.16,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V
4764,SPCC736.05,wtf7,wtf element Wtf7,protein coding gene,SPCC736.05,NaN,NO_CHANGE,NaN,V,V,SPCC1183.10|SPCC1281.08|SPCC1450.08c|SPCC162.0...,NaN,NaN,NaN
4777,SPCC737.04,SPCC737.04,UPF0300 family protein 6,protein coding gene,SPCC737.04,NaN,NO_CHANGE,NaN,V,V,SPAC10F6.15|SPAC4G9.07|SPBC1861.06c|SPCC1259.1...,NaN,NaN,NaN
4879,SPCC970.11c,wtf9,wtf antidote-like meiotic drive suppressor Wtf9,protein coding gene,SPCC970.11c,NaN,NO_CHANGE,NaN,V,V,SPCC1183.10|SPCC1281.08|SPCC1450.08c|SPCC162.0...,NaN,NaN,NaN
4912,SPCPJ732.03,meu15,Schizosaccharomyces pombe specific protein Meu15,protein coding gene,SPCPJ732.03,SPCPJ732.03,NO_CHANGE,NO_CHANGE,NaN,NaN,NaN,"VIABLE WT cells at 25,32",WT,V